### ISSUE TITLE
Some Problems on the Conversion of pptx (ppt) into HTML 

### ISSUE THREAD

**Issue by ZCHWorld** [aspose-slides/Aspose.Slides-for-Java#25]
Hello, everybody. When I use Aspose slides to convert pptx to html, I found some problems of overlapping text misplacement. Is my method wrong? Here is an example link 
![捕获](https://user-images.githubusercontent.com/23251207/63037336-82101a80-bef1-11e9-9bb7-2b08b3662300.PNG)
[demo](https://github.com/ZCHWorld/aspose-slides-issue)

**Comment by ZCHWorld** [comment]
Supplementary picture 
![捕获](https://user-images.githubusercontent.com/23251207/63037243-45442380-bef1-11e9-8902-d75429635d9e.PNG)

**Comment by mannanfazil** [comment]
@ZCHWorld 
We are working on your query and will get back to you soon.

**Comment by mannanfazil** [comment]
@ZCHWorld 

We tested the scenario and have managed to reproduce the same problem on our end. For the sake of correction, we have logged the following issue in our issue tracking system. The ID of this issue is SLIDESJAVA-37732.
We will further look into the details of this problem and will keep you updated on the status of correction. We apologize for your inconvenience.

**Comment by ZCHWorld** [comment]
**Thank you for your attention！**

**Comment by andreypotapovaspose** [comment]
@ZCHWorld,
The issues you have found earlier (filed as SLIDESJAVA-37732) have been fixed in this [update](https://downloads.aspose.com/slides/java/new-releases/aspose.slides-for-java-20.9/). You can use the latest version of [Aspose.Slides](https://downloads.aspose.com/slides/java) already.
